config/routes.rb
Hostess::Application.routes.draw do
  # include devise routes
  devise_for :users
  
  # root route
  root :to => "Admin#design"

  #Services routes:
  namespace :services do
    #resources :users
    resources :restaurants, :only => [:index, :show] do
      collection do
        get 'near/:position', :action=>'all_near_position', :constraints => {:position => /\-*\d+.?\d*,\-*\d+.?\d*/}
        get 'search', :action=>'search'
        get 'favorites/:udid', :action=>'favorites', :constraints => {:udid => /\w{0,128}/}
        post 'favorites/:udid/:restaurant_id', :action=>'add_to_favorites', :constraints => {:udid => /\w{0,128}/,:special_id => /\d+/}
        delete 'favorites/:udid/:restaurant_id', :action=>'remove_from_favorites', :constraints => {:udid => /\w{0,128}/,:special_id => /\d+/}
        # do not erase this line, this will allow the services to send a message instead of displaying the error page
      end
    end
    resources :specials, :only => [:index, :show] do
      collection do 
        get 'restaurants/:id/:udid', :action=>'list_by_restaurant', :constraints => {:udid => /\w{0,128}/}
        get 'favorites/:udid', :action=>'favorites', :constraints => {:udid => /\w{0,128}/}
        post 'favorites/:udid/:special_id', :action=>'add_to_favorites', :constraints => {:udid => /\w{0,128}/,:special_id => /\d+/}
        delete 'favorites/:udid/:special_id', :action=>'remove_from_favorites', :constraints => {:udid => /\w{0,128}/,:special_id => /\d+/}
        get 'redeem/:udid/:special_id', :action=>'redeem', :constraints => {:udid => /\w{0,128}/,:special_id => /\d+/}
        # do not erase this line, this will allow the services to send a message instead of displaying the error page
      end
    end
    resources :food_categories, :only => [:index]
    resources :notifications, :only => [:register] do 
      collection do 
        get 'register', :action=>'register'
        # do not erase this line, this will allow the services to send a message instead of displaying the error page
      end
    end
    # do not erase this line, this will allow the services to send an error message instead of displaying the old fashion error page
    match '*a', :to=>'errors#routing'
  end
  
  #specific routes
  match 'content/about'
  match 'content/help'  
  match 'content/privacyPolicy'
  match 'content/termsOfService'
  
  match 'admin/design'
  match 'admin/my_info'
  match 'admin/refresh_design'
  match 'admin/specials'
  match 'admin/refresh_special'
  match 'admin/analytics'
 
  match 'admin/signup/step1'
  match 'admin/signup/step2'
  match 'admin/signup/step3'
  match 'admin/signup/thank_you'
  
  match 'account_settings', :controller => "account_settings", :action => "index"
  match 'account_settings/update_name'
  match 'account_settings/update_email'
  match 'account_settings/update_subscription'
  match 'account_settings/update_password'
  match 'account_settings/update_billing_info'
  
end

app/views/shared/_allow_tutorial_popup.js.erb
jQuery("a#popupTutorial").fancybox({
	'hideOnContentClick': false,
	'padding': 0
});

app/views/shared/_cancel_subscription_confirmation_popup.erb
<div id="cancel_subscription_confirmation_div" style="display: none">
	<a id="showCancelSubscriptionConfirmationPopup" href="#cancelSubscriptionConfirmation"></a>
	<div id="cancelSubscriptionConfirmation" class="popUpWindow">
		<div class="popUpWindowTitle loraItalic14pt291911">Cancel you Subscription!<br /><br /></div>
		<div id="confirmationContent" class="popUpWindowContent arialBold15ptEFE7D3" style="text-align:center;">Account will be cancelled immediately.  No partial payment will be refunded</div>
		<br /><br />
		<div id="yesCancelSubscriptionBtn"></div>		
		<div id="noCancelSubscriptionBtn"></div>
		<br />
	</div>
</div>

app/views/shared/_delete_confirmation_popup.erb
<div id="delete_confirmation_div" style="display: none">
	<a id="showDeleteConfirmationPopup" href="#deleteConfirmation"></a>
	<div id="deleteConfirmation" class="popUpWindow">
		<div class="popUpWindowTitle loraItalic14pt291911">Confirm Delete?<br /><br /></div>
		<div id="confirmationContent" class="popUpWindowContent arialBold15ptEFE7D3" style="text-align:center;">Are you sure you want to delete this<br />Special and all of its contents?</div>
		<br /><br />
		<div id="confirmDeleteBtn"></div>		
		<div id="confirmDeleteCancelBtn"></div>
		<br />
	</div>
</div>

app/views/shared/_errors_popup.erb
<div id="errors_div" style="display: none">
	<a id="showErrors" href="#errors"></a>
	<div id="errors" class="popUpWindow">
		<div class="popUpWindowTitle loraItalic14pt291911">Oops...<br /><br /></div>
		<div id="errorContent" class="popUpWindowContent arialBold15ptEFE7D3"></div>		
		<div id="errorButtonOk"></div>
	</div>
</div>

app/views/shared/_footer.html.erb
<div id="footer" class="span-32 last">
	<h1 class="arial10pt291911" >Copyright &copy; 2011 Hostess, Inc.</h1>
	<%= link_to "ABOUT", { :controller => "/content", :protocol => "http://", :action => "about"}, :class => "loraBld12pt291911" + (' linkOpen' if params[:action] == 'about').to_s %>
	<%= link_to "MOBILE", 'http://www.myhostessapp.com/', :class => "loraBld12pt291911"%>	
	<%= link_to "PRIVACY", { :controller => "/content", :protocol => "http://", :action => "privacyPolicy"}, :class => "loraBld12pt291911" + (' linkOpen' if params[:action] == 'privacyPolicy').to_s%>
	<%= link_to "HELP", { :controller => "/content", :protocol => "http://", :action => "help"}, :class => "loraBld12pt291911" + (' linkOpen' if params[:action] == 'help').to_s%> 
</div>

app/views/shared/_head.html.erb
<head>
	<title>Hostess</title>
	<%= stylesheet_link_tag :all %>
	<link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic' rel='stylesheet' type='text/css'>
	
	
	<%= javascript_include_tag :all %>
	<script type="text/javascript" src="/javascripts/fgMenu/fg.menu.js"></script>
	<script type="text/javascript" src="/javascripts/jquery.fancybox-1.3.4.pack.js"></script>
	<script type="text/javascript" src="/javascripts/jquery.easing-1.3.pack.js"></script>
	<%= csrf_meta_tag %>
	
	<!-- #fonts-->
	<%= yield :head%>
	
</head>

app/views/shared/_header.html.erb
<div id="header" class="span-32 last" style="color:#FFFFFF">
	<% if user_signed_in? %>
	<div class="userOptions">
		<a id="flat" tabindex="0" href="#user-options" class="fg-button" > <span class="fb-icon"></span>Welcome <%= current_user.email %></a>
		<div id="user-options" class="hidden">
			<ul>
				<li>
					<%= link_to("Account Settings", account_settings_path, :class => "marginLeft5") %>
				</li>
				<li>
					<%= link_to("Sign out", destroy_user_session_path,:class => "marginLeft5", :method => :delete ) %>
				</li>
			</ul>
		</div>
	</div>
	<%elsif params[:action] == 'about' or params[:action] == 'privacyPolicy' or params[:action] == 'termsOfService' or params[:action] == 'help'%>
	<div class="userOptions">
		<br />
		<%=link_to("Sign In", "/", :class => "fg-button") %>
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		<%=link_to("Sign Up Now", { :controller=> "admin/signup", :protocol => "http://", :action => "step1"}, :class => "fg-button") %>
	</div>	
	
	<% end %>
	
	
	
</div>

app/views/shared/_navMenu.html.erb
<div class="navMenu">
	<%unless current_user.nil?%>
		<%if params[:action] == 'design'%>
		<div class="designMenuBtnSelected"></div>
		<%= link_to("", { :controller => "admin", :protocol => "http://", :action => "analytics"}, :class => "analyticsMenuBtn") %>
		<%elsif params[:action] == 'analytics'%>
		<%= link_to("", { :controller => "admin", :protocol => "http://", :action => "design"}, :class => "designMenuBtn") %> <div class="analyticsMenuBtnSelected"></div>
		<%else%>
		<%= link_to("", { :controller => "admin", :protocol => "http://", :action => "design"}, :class => "designMenuBtn") %>
		<%= link_to("", { :controller => "admin", :protocol => "http://", :action => "analytics"}, :class => "analyticsMenuBtn") %>
		<%end%>
		<%if current_user.arb_status != AuthorizeNet::ARB::Subscription::Status::ACTIVE %>
		<div id="arbMessage" class="arial14ptEFE7D3 ">* Your account has <span style="color:red;">expired</span>. Please update your billing information in <%= link_to("Account Settings", account_settings_path, :class => "arialUln14pt8CA671") %>.</div>
		<%end%>
	<%end%>
	
</div>

app/views/shared/_send_notifications_confirmation_popup.erb
<div id="send_notification_confirmation_div" style="display: none">
	<a id="showSendNotificationsConfirmationPopup" href="#notificationConfirmation"></a>
	<div id="notificationConfirmation" class="popUpWindow">
		<div class="popUpWindowTitle loraItalic14pt291911">Changes Saved!<br /><br /></div>
		<div id="confirmationContent" class="popUpWindowContent arialBold15ptEFE7D3" style="text-align:center;">Would you like to notify subscribed customers of this updated special?</div>
		<br /><br />
		<div id="sendNotificationOkBtn"></div>		
		<div id="sendNotificationCancelBtn"></div>
		<br />
	</div>
</div>

app/views/shared/_tutorial.html.erb
<div id="tutorial">
	<div id="tutorialPage1">
		<div class="top">
			<span class="lora28pt68804D">Welcome to Hostess</span>
			<br />
			<p class="arial17pt291911">Follow these simple steps to set up your business in a matter of minutes!</p>
			<br />
			<span class="loraItalic16pt8CA671"> Create a Restaurant Profile</span>
			<br />
			<p class="arial16pt291911 recomendation">To best promote your restaurant, we recommend filling out all categories although not all are required. Entering your business name, adding pictures, tags, and more couldn't be more simple. You can also select categories that are associated with your restaurant.</p>
		</div>
		<div class="below marginTop5">
			<div id="left" class="marginTop5">
				<br />
				<span class="loraItalic16pt8CA671">Upload Photo(s) and Video</span>
				<br />
				<p class="arial16pt291911">Upload photos and video simply by selecting the file  you want to upload in the General Info section. File sizes are limited to 5mb.</p>
				<br />
				<span class="loraItalic16pt8CA671 marginTop5">Preview/Save</span>
				<br />
				<p class="arial16pt291911">Clicking the preview button will let you preview how your information will display on the phone before anyone can see it. The save button will save the current information and make it viewable by Hostess users.</p>
			</div>
			<div id="right">
			</div>			
		</div>
		<div id="nextButton">
			<span style="margin-left:750px;"><img class="arrowButton" src="/images/buttons/button_brown_rightarrow.png" onclick="nextClickOnTutorial();"></span>
		</div>
	</div>	
	<div id="tutorialPage2" style="display:none;">
		<div class="top">
			<span class="loraItalic16pt8CA671">Post Specials</span>
			<br />
			<p class="arial16pt291911 recomendation">Show and tell your guests why you are special. Highlight menu specials and events. Be creative! Under the specials tab, you can add a special by clicking the [+] button. Fill out the special's name, description, add a start and end date, and a photo.</p>
			<span class="loraItalic16pt8CA671">Add Tags</span>
			<br />
			<p class="arial16pt291911 recomendation">Adding tags helps users find your business. Add a few tags that users may use to find your business. For example, if you're a fast food burger joint, you may want to use tags like "Burgers", "Local", "Vegetarian", "Drive-Thru", etc.</p>
		</div>
		<div class="below">
			<div id="left">
				<span class="loraItalic16pt8CA671">View Analytics</span>
				<br />
				<p class="arial16pt291911">This section lets you track all the analytics you need to optimize your specials and maximize customer traffic. Statics such as "Number of Impressions" and "Most Viewed Featured Special" let you know which specials are working and why.</p>				
				<span class="loraItalic16pt8CA671">Your Account</span>
				<br />
				<p class="arial16pt291911">If you're looking to sign out or change your account details, click on your name at the upper right. If you have questions try looking for your question in the Help section.</p>
				<p class="arial16pt291911">Now get out there and grow your business!</p>				
			</div>
			<div id="right2">
			</div>
			
		</div>
		<div id="backButton">
			<span style="margin-left:20px;"><img class="arrowButton" src="/images/buttons/button_brown_leftarrow.png" onclick="backClickOnTutorial();"></span>			
		</div>
	</div>
</div>